// Curriculum Knowledge Base loader. Static, exam-agnostic content only —
// chapter/topic trees generated by scripts/build-curriculum.mjs into ./data.
// No student state lives here, ever.
//
// Subject files are loaded through import.meta.glob so Vite emits each one as
// its own lazy chunk: a student's phone downloads only the subjects they use,
// and the hashed chunks precache for offline like any other build asset.

import manifest from './data/index.json'

const subjectModules = import.meta.glob('./data/ncert/*/*.json')

const cache = new Map()

export function loadManifest() {
  return manifest
}

// Manifest rows for a board+class (no tree data loaded).
export function subjectsFor(board, cls) {
  return manifest.subjects.filter((s) => s.class === cls && s.boards.includes(board))
}

function manifestRow(cls, subject) {
  return manifest.subjects.find(
    (s) => s.class === cls && (s.subject === subject || s.subjectCode === subject)
  )
}

// Async: the chapter tree for a class + subject (display name or code).
// Cached after first load. Returns null for subjects the CKB doesn't have.
export async function loadSubject(cls, subject) {
  const row = manifestRow(cls, subject)
  if (!row) return null
  if (!cache.has(row.path)) {
    const mod = await subjectModules[`./data/${row.path}`]()
    cache.set(row.path, mod.default)
  }
  return cache.get(row.path)
}

// Sync: only what's already been loaded. Callers that need a guarantee should
// await loadSubject (or preloadSubjects) first.
export function getSubject(cls, subject) {
  const row = manifestRow(cls, subject)
  return row ? cache.get(row.path) ?? null : null
}

// Warm the cache for a set of subjects (e.g. the student's own at app start —
// each file is a few KB of JSON).
export function preloadSubjects(cls, subjects) {
  return Promise.all(subjects.map((s) => loadSubject(cls, s)))
}
