// Turn a UDISE+ "Know Your School" JSON response into a seed migration.
//
//   node scripts/seed-schools.mjs scratch/daman-schools.json > supabase_schools_seed_daman.sql
//
// Pass more than one file if the portal paginated the district across pages.
//
// Only operational schools are seeded. UDISE keeps merged and permanently
// closed schools in the same response, and a student must never be able to
// pick a school that no longer exists.

import { readFileSync } from 'node:fs'

const STOPWORDS = new Set(['of', 'the', 'and'])
const OPERATIONAL = 0

// Mirrors the `name_key` generated column in supabase_schools.sql. Kept here so
// we can detect a collision before Postgres does, mid-insert.
const nameKey = (n) => n.replace(/[^a-zA-Z0-9]+/g, '').toLowerCase()

const clean = (n) => n.trim().replace(/\s+/g, ' ').replace(/[.,\s]+$/, '')

const titleCase = (s) =>
  s.toLowerCase().replace(/\b[a-z]/g, (m) => m.toUpperCase())

// Initials of the significant words. UDISE stores "INS. OF OUR LADY OF FATIMA",
// students type IOLF. Dropping stopwords is what makes those line up.
function acronym(name) {
  return clean(name)
    .split(/[^A-Za-z0-9]+/)
    .filter((t) => t && !STOPWORDS.has(t.toLowerCase()))
    .map((t) => t[0])
    .join('')
    .toUpperCase()
}

const sqlStr = (s) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`)
const sqlNum = (n) => (n == null ? 'null' : String(n))
const sqlArr = (xs) =>
  xs.length ? `array[${xs.map(sqlStr).join(', ')}]` : `'{}'::text[]`

const files = process.argv.slice(2)
if (!files.length) {
  console.error('usage: node scripts/seed-schools.mjs <udise.json> [more.json ...]')
  process.exit(1)
}

const rows = files
  .flatMap((f) => JSON.parse(readFileSync(f, 'utf8')).data.content)
  .filter((r) => r.schoolStatus === OPERATIONAL)
  .map((r) => ({
    udise: String(r.udiseschCode),
    name: clean(r.schoolName),
    district: titleCase(r.districtName),
    // "DADRA & NAGAR HAVELI AND DAMAN & DIU" -> readable, with `and` kept lower.
    state: titleCase(r.stateName).replace(/\bAnd\b/g, 'and'),
    gradeFrom: r.classFrm ?? null,
    gradeTo: r.classTo ?? null,
    // UDISE addresses are shouted; the search result renders them inline.
    address: r.address ? titleCase(clean(r.address)) : null
  }))

// Two schools sharing a name_key in one district would violate the unique index
// and abort the whole seed. Fail loudly here instead.
const seen = new Map()
for (const r of rows) {
  const k = `${nameKey(r.name)}|${r.district}`
  if (seen.has(k)) {
    console.error(`name_key collision: ${seen.get(k).name} vs ${r.name}`)
    process.exit(1)
  }
  seen.set(k, r)
}

// A 2-3 letter acronym off an already-abbreviated name ("GHS DUNETHA" -> "GD")
// is noise that collides with four other schools. Keep only the long, unique
// ones -- those are the ones students actually type.
const counts = new Map()
for (const r of rows) {
  const a = acronym(r.name)
  counts.set(a, (counts.get(a) || 0) + 1)
}
for (const r of rows) {
  const a = acronym(r.name)
  r.aliases = a.length >= 4 && counts.get(a) === 1 && nameKey(a) !== nameKey(r.name) ? [a] : []
}

const values = rows
  .map(
    (r) =>
      `  (${sqlStr(r.udise)}, ${sqlStr(r.name)}, ${sqlStr(r.district)}, ${sqlStr(r.state)}, ` +
      `${sqlArr(r.aliases)}, ${sqlNum(r.gradeFrom)}, ${sqlNum(r.gradeTo)}, ${sqlStr(r.address)}, true)`
  )
  .join(',\n')

const withAlias = rows.filter((r) => r.aliases.length).length

process.stdout.write(`-- SmartRevision — school seed: ${rows[0].district}
-- Generated by scripts/seed-schools.mjs from UDISE+ Know Your School.
-- ${rows.length} operational schools; ${withAlias} carry a derived acronym alias.
-- Re-runnable: conflicts on udise_code are refreshed, not duplicated.

insert into schools (udise_code, name, district, state, aliases, grade_from, grade_to, address, verified) values
${values}
on conflict (udise_code) do update
  set name = excluded.name,
      district = excluded.district,
      state = excluded.state,
      aliases = excluded.aliases,
      grade_from = excluded.grade_from,
      grade_to = excluded.grade_to,
      address = excluded.address,
      verified = true;
`)

console.error(`${rows.length} operational schools, ${withAlias} with aliases`)
for (const r of rows.filter((r) => r.aliases.length)) {
  console.error(`  ${r.aliases[0].padEnd(8)} ${r.name}`)
}
